apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
